name: XPShare
version: '${project.version}'
main: me.dg.xpshare.XPShare
api-version: 1.17
authors: [ Daniel_Garcia, Kenley_Ruiz ]
description: Store, get, share player xp
website: https://github.com/Dg0222/XPShare_Minecraft_Plugin
commands:
    storexp:
      description: Stores current player Xp
      usage: /<command> [integer]
    getxp:
      description: Get player Xp that was stored
      usage: /<command> [integer]
    storedxp:
      description: Shows player Xp that is currently stored
      usage: /<command>
    sharexp:
      description: Share Xp with another player
      usage: /<command> [player] [integer]
